feat: add blog & service & testimonials models
RythmTechnologies/Company-Promotion pull request #6
Opened 2024-02-16 15:16 UTC by CoderMungan

2024-02-17 19:37 UTC, enescomruk72 commented on company/apps/blog/models.py
> +  slug = AutoSlugField(
Here populate_from should be name, not title

2024-02-17 19:38 UTC, enescomruk72 commented on company/apps/blog/models.py
> +    return self.title
gj

2024-02-17 19:38 UTC, enescomruk72 commented on company/apps/service/models.py
> +      return self.title
ok

2024-02-17 19:38 UTC, enescomruk72 commented on company/apps/testimonials/models.py
> +      return self.author
ok for now

2024-02-17 19:39 UTC, enescomruk72 requested changes
slug = AutoSlugField(
        populate_from="title", editable=False, always_update=True, blank=True
    )
    
    Here populate_from should be name, not title

2024-02-17 19:55 UTC, CoderMungan commented on company/apps/blog/models.py
> +  slug = AutoSlugField(
[fb0afc6](https://github.com/RythmTechnologies/Company-Promotion/pull/6/commits/fb0afc6bcbd20ac86efb30895dd1ffe12b4a8acb) ow i see that and changed !

2024-02-17 19:55 UTC, CoderMungan commented on company/apps/blog/models.py
> +    return self.title
ty

2024-02-17 19:55 UTC, CoderMungan commented on company/apps/testimonials/models.py
> +      return self.author
ty

2024-02-17 19:55 UTC, CoderMungan commented
> slug = AutoSlugField( populate_from="title", editable=False, always_update=True, blank=True )
> 
> ```
> Here populate_from should be name, not title
> ```

[fb0afc6](https://github.com/RythmTechnologies/Company-Promotion/pull/6/commits/fb0afc6bcbd20ac86efb30895dd1ffe12b4a8acb)

2024-02-18 11:48 UTC, mciray commented on company/apps/blog/models.py
> +    return self.title
nice job

2024-02-18 11:48 UTC, mciray commented on company/apps/service/models.py
> +      return self.title
well done

2024-02-18 11:49 UTC, mciray approved these changes
lgtm

2024-02-19 19:18 UTC, merged